#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Test
        run: mvn --batch-mode --update-snapshots --no-transfer-progress test

      - name: Extract Coverage Percentage
        run: |
          coverage=$(grep -oP '<td class="ctr2">\K(\d+)%' target/coverage-reports/index.html | head -n 1)
          coverage=${coverage%\%}
          echo "COVERAGE_PERCENTAGE=$coverage" >> $GITHUB_ENV

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 25ee2912e257798cd44abb981b25f9a7
          filename: coverage.json
          label: Coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}%
          valColorRange: ${{ env.COVERAGE_PERCENTAGE }}
          maxColorRange: 100
          minColorRange: 0